version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tpv-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tpvdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Scripts SQL al iniciar
    networks:
      - tpv-net

volumes:
  pgdata:

networks:
  tpv-net:
    driver: bridge
